#!/bin/bash

echo "🚀 AilaBank Arc Testnet Deployment - Quick Start"
echo "=================================================="
echo ""
echo "📋 What you need:"
echo "   1. ✅ Wallet with private key"
echo "   2. ✅ Testnet USDC for gas (from faucet)"
echo "   3. ✅ USDC token address on Arc"
echo ""
echo "🔧 Setup Commands:"
echo ""
echo "# 1. Generate wallet"
echo "npx ts-node scripts/generate-wallet.ts"
echo ""
echo "# 2. Check readiness"
echo "npx ts-node scripts/check-deployment-readiness.ts"
echo ""
echo "# 3. Deploy contracts"
echo "npx hardhat run scripts/deploy.ts --network arc"
echo ""
echo "📍 Important Links:"
echo "   Faucet:   https://faucet.circle.com (select Arc Testnet)"
echo "   Explorer: https://testnet.arcscan.app"
echo "   RPC:      https://rpc.testnet.arc.network"
echo ""
echo "💡 Remember: USDC is the native gas token on Arc!"
echo ""
